name: Keep Chatbot Warm

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping chatbot health check
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://foodimetric-bot.onrender.com/
